### ISSUE TITLE
[BUG] Editor rulers not taken into account over 80

### ISSUE THREAD

**Issue by wimille** [gdesnoues/complete-line#1]
Hi,

i discovered your extension a few hours ago, it seems very useful. However, i've encountered an weird behavioral. 
In my parameters file, i define the following rulers:
```
// Regles
  "editor.rulers": [90,110,120],
```

However when i use the extension with the keyboard shortcut it fills the line with the selected characters until column 80, no more. If i try to use it at column 80, extension tells me that the line length is over 80.

Did i missed some configuration or is it a real issue ?

Best regards

**Comment by gdesnoues** [comment]
Hi,
Thanks for your feedback.
This is a normal behavior : the info on how to set up vertical lines is completely independent of my plugin. You can use it without installing the plugin.

To define the length of the commented lines plugin, go to `Settings > Extensions > Complete Line` and fill in the Desired Length field.

Your info is at least interesting, I will see if it's possible to implement this feature to allow multi-completion lenghts lines
Stay turned.

Best regards

**Comment by wimille** [comment]
Hi,

I understand my mistake. On the extension page on github you've mentionned the ruler we can define in vscode. And i thought that your extension used this definition, but in fact, you had just mentionned how to setup the rulers in vscode.

Well, for now, i'll configure my favorite line lenght in my JSON parameters file and keep use your extension.

Hope you'll find a way to use the vscode ruler definition.

Best regards.

**Comment by wimille** [comment]
Hi,

I've made a little modification on your extension to take into account the editor rulers configuration. It seems to work fine. However i don't know the correct way to send you a patch on Github.

**Comment by ppo** [comment]
I don't know if that's the behavior @wimille implemented but it would be great to loop through each ruler value that is > to the line length.

So in your example:

- Line with less than 90 characters: 90, 110, 120, then back to 90.
- Line with 90-109 characters: 110, 120, 110.

**Comment by ppo** [comment]
It would also make sense to use the Prettier width `prettier.printWidth`.

**Comment by gdesnoues** [comment]
Absent for a long time, I will take up this request again and see how to integrate it.

**Comment by gdesnoues** [comment]
I have added this issue in the v1.2.0
Thanks @wimille for your PR, i have change some lines to add the setting param to the array.
So now we can have several step : rules and setting param.
