### ISSUE TITLE
Suggestion: Repeat last character of the line

### ISSUE THREAD

**Issue by ppo** [gdesnoues/complete-line#3]
Instead of defining the character to repeat in the settings, use the last character of the line.

That way we can repeat any character without having to make a selection… which requires to many actions :wink:

So we can just type `// Heading -` and hit the command shortcut keys.

**Comment by gdesnoues** [comment]
That's a good idea!
I'll see how to implement it without removing the possibility to set the character in the parameters.
Maybe with a checkbox or a keyword in the field

**Comment by ppo** [comment]
If no value (empty string) defined in settings, use last character. Default: empty.

(And same thing for width.)
