### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by ppo** [gdesnoues/complete-line#4]
- `chose` > `choose`
- `repete`/`repeted` > `repeat`/`repeated`
- `clic` > `click`

PS: Francophone je suppose? :wink:

**Comment by gdesnoues** [comment]
Oui en effet ;-)
Je vais modifier, merci

**Comment by ppo** [comment]
Il y a le même genre d'erreurs dans l'écran de config… au moins t'es consistant :wink:  
Donc ce serait bien de faire une petite recherche dans tous les fichiers.
